### PR TITLE
0.1.5

### PR DESCRIPTION
**Pull request by Ddystopia**

### CODE REVIEW

**Comment by ic-it** [comment]
What target of this PR?

**Comment by Ddystopia** [comment]
> What target of this PR?

Optimizations, internal improvements, etc

**Comment by Ddystopia** [comment]
There should be some life in the repo)

**Comment by ic-it** [comment]
Reasonable

**Review by ic-it — APPROVED** [review]
LGTM

**Comment by Ddystopia** [comment]
> LGTM

Hope you will report future panics

**Pull request merged**
